### PR TITLE
A /getserverinfo command

### PR DESCRIPTION
**Pull request by kyle95wm**
This will come in handy for cases where people ask things like "what server are you in?" and other similar questions.

### CODE REVIEW

**Review by thewilloftheshadow — CHANGES_REQUESTED** [review]
You'll need to add it to src/commands/index.ts as well

**Comment by kyle95wm** [comment]
I believe that should do it

**Comment by thewilloftheshadow** [comment]
Add it in the array on line 8 as well then it should be good

**Review by thewilloftheshadow — CHANGES_REQUESTED** [review]
^

**Pull request merged**
